version: "3.8"
services:
  cache:
    image: redis/redis-stack:7.2.0-v6
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  stripe:
    image: "stripe/stripe-cli"
    command:
      [
        "listen",
        "--forward-to",
        "http://host.docker.internal:4300/api/webhooks/stripe",
      ]
    environment:
      - STRIPE_DEVICE_NAME=docker-compose
      - STRIPE_API_KEY=sk_test_51On1nRHnJcBv7Ja08ShGqHkahbBh8iz6XLdSdzrBYzG2AIWqSSloIeM5TdMqscSe6dcmeqvlGa6HT4yHM6ErwS5Y0065jnHXnn
