import './global.scss';

import { AppContainer } from '@021software/pattern-library/core';

export const metadata = {
  title: 'Welcome to dankai',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContainer>{children}</AppContainer>
      </body>
    </html>
  );
}
